### ISSUE TITLE
Details on PDB board production

### ISSUE THREAD

**Issue by YB17** [moribots/minitaur_from_scratch#15]
I'm trying to reproduce the project. However I'm not that into PCB design, and while being able to understand the PDB design at a high level I am not able to fulfill some details. It would be great if you can provide a BOM for the single-power version, or if you could help me with the following questions please:

1. in the single power version there are four slots for "resistors" -- what type and size (ohm) should I use for each resistor?
2. if I use the servo as suggested in the list (JX CLS6336 Servo (36KG)), what is the suggested size of the capacitors? Or any between 100uF and 470 uF is fine?
3. What are the usage of S1, S2, S3, S4 ? Are they for the hall sensor connections?
4. It is mentioned that hall sensor slots are added on the feet, but there is no hall sensor listed on the BOM? are they still in the TODO list?

Thanks!

**Comment by moribots** [comment]
1. The resistors are for the contact sensors, I think they require 10kOhm. I didn't end up using them.
2. If you can get 470uf, you'll get better results than with 100uf.
3. You are correct. These are optional.
4. Yep, I didn't end up using them because they were not reliable, but there's no reason to remove them from the PDB.

**Comment by YB17** [comment]
Thanks for the information!
